{
  mulchOrders(spreaderId: "gletourneau", excludeOwnerId: "gletourneau", doGetSpreadOrdersOnly: true) {
    orderId
    ownerId
    customer {
        addr1
        neighborhood
    }
    purchases {
        productId
        numSold
    }
    spreaders
  }
}
