{
  mulchTimecards{
    id,
    timeTotal
  }
  mulchOrders {
    ownerId
    purchases {
        productId
        numSold
        amountCharged
    }
    amountFromDonations
    amountTotalCollected
    spreaders
  }
}
