{
  config {
    description
    kind
    isLocked
    lastModifiedTime
    neighborhoods {
      name
      distributionPoint
    }
    mulchDeliveryConfigs {
      id
      date
      newOrderCutoffDate
    }
    products {
      id
      label
      unitPrice
      minUnits
      priceBreaks {
        gt
        unitPrice
      }
    }
    finalizationData {
      bankDeposited
      mulchCost
      perBagCost
      profitsFromBags
      mulchSalesGross
      moneyPoolForTroop
      moneyPoolForScoutsSubPools
      moneyPoolForScoutsSales
      moneyPoolForScoutsDelivery
      perBagAvgEarnings  
      deliveryEarningsPerMinute
    }
    users {
      id
      name
    }
  }
}
