mutation {
  updateConfig(config: {
    products: [
      {
          id: "bags",
          label: "Bags of Mulch",
          unitPrice: "4.65",
          minUnits: 5,
          priceBreaks: [
              {
                  gt: 15,
                  unitPrice: "4.50"
              },{
                  gt: 35,
                  unitPrice: "4.35"
              },{
                  gt: 64,
                  unitPrice: "4.25"
              }
          ]
      },{
          id: "spreading",
          label: "Bags to Spread",
          unitPrice: "2.00"
      }
    ]
  })
}
