mutation {
  updateNeighborhoods( neighborhoods: [
    {
       name: "Brushy Creek (Cedar Park)",
       city: "Cedar Park",
       zipcode: 78613,
       isVisible: true,
       distributionPoint: "Walsh"
    }
  ])
}
