
mutation {
  setUsers(users: [{
    id: "fradmin"
    group: "Bear"
    name: "Super User"
  },{
    id: "fruser1"
    group: "Eagle"
    name: "User One"
  },{
    id: "fruser2"
    group: "Cobra"
    name: "User Two"
  },{
    id: "fruser3"
    group: "Cobra"
    name: "User Three"
  },{
    id: "fruser4"
    group: "Eagle"
    name: "User Four"
  }])
v
