{
  summary {
    orderOwner(ownerId: "nsalinas") {
      totalDeliveryMinutes
      totalAssistedSpreadingOrders
      totalNumBagsSold
      totalNumBagsSoldToSpread
      totalAmountCollectedForDonations
      totalAmountCollectedForBags
      totalAmountCollectedForBagsToSpread
      totalAmountCollected
      allocationsFromDelivery
      allocationsFromBagsSold
      allocationsFromBagsSpread
      allocationsTotal
    }
    troop(numTopSellers: 10) {
      totalAmountCollected
      topSellers {
        totalAmountCollected
        name
      }
      groupSummary {
        groupId
        totalAmountCollected
      }
    }
  }
}
