name: Build Go Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  GOOS: linux
  GOARCH: arm64
  CGO_ENABLED: 0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build and package Lambda
        run: |
          cd ./cmd/lambda
          go build -ldflags="-s -w" -tags lambda.norpc -o dist/bootstrap
          cd dist
          zip function.zip bootstrap root.crt

