name: Build Go Lambda

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  GOOS: linux
  GOARCH: arm64
  CGO_ENABLED: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            # This caches downloaded module files (not the built ones)
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build and package Lambda
        run: |
          cd ./cmd/lambda
          go build -ldflags="-s -w" -tags lambda.norpc -o dist/bootstrap

